name: Bug Report
description: Report a bug or unexpected behavior in the Replane .NET SDK
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Initialize client with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of the .NET SDK are you using?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      description: What version of .NET are you using?
      options:
        - .NET 9
        - .NET 8
        - .NET 7
        - .NET 6
        - Other
    validations:
      required: true

  - type: dropdown
    id: project-type
    attributes:
      label: Project Type
      description: What type of .NET project are you using?
      options:
        - ASP.NET Core Web API
        - ASP.NET Core MVC
        - Blazor
        - Console Application
        - Worker Service
        - MAUI
        - WPF
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment details (OS, IDE, hosting, etc.)
      placeholder: |
        - OS: Windows 11 / macOS 14 / Linux
        - IDE: Visual Studio 2022 / Rider / VS Code
        - Hosting: Azure / AWS / Self-hosted
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code to reproduce the issue.
      render: csharp
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Output / Stack Trace
      description: Please copy and paste any relevant error messages or stack traces.
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

